### ISSUE TITLE
`pip install ebcdic` fails with 'ValueError: path ... cannot be absolute'

### ISSUE THREAD

**Issue by Jakub-CZ** [roskakori/CodecMapper#11]
```
OS: Windows
ebcdic version: 1.0.2
```

In Windows, installation of ebcdic fails with `ValueError: path '/Users/roskakori/workspace/CodecMapper/LICENSE.txt' cannot be absolute`.
Last version that can be installed successfully is 1.0.0.

For Linux, everything seems to work fine.

<details>
<summary>Below is full console output</summary>
<p>

```
λ pip install ebcdic
Looking in indexes: https://pypi.org/simple, xxxxx
Collecting ebcdic
  Using cached https://files.pythonhosted.org/packages/10/61/d653aef932cca6621c763a58e29f74dd7123118011b94266de518f5433a8/ebcdic-1.0.2.zip
Building wheels for collected packages: ebcdic
  Building wheel for ebcdic (setup.py) ... error
  ERROR: Complete output from command 'C:\Miniconda2\envs\test\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-f8enp8mw\\ebcdic\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-lil2pcak' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\ebcdic
  copying ebcdic\cp037.py -> build\lib\ebcdic
  copying ebcdic\cp1025.py -> build\lib\ebcdic
  copying ebcdic\cp1047.py -> build\lib\ebcdic
  copying ebcdic\cp1097.py -> build\lib\ebcdic
  copying ebcdic\cp1112.py -> build\lib\ebcdic
  copying ebcdic\cp1122.py -> build\lib\ebcdic
  copying ebcdic\cp1123.py -> build\lib\ebcdic
  copying ebcdic\cp1140.py -> build\lib\ebcdic
  copying ebcdic\cp1141.py -> build\lib\ebcdic
  copying ebcdic\cp1142.py -> build\lib\ebcdic
  copying ebcdic\cp1143.py -> build\lib\ebcdic
  copying ebcdic\cp1144.py -> build\lib\ebcdic
  copying ebcdic\cp1145.py -> build\lib\ebcdic
  copying ebcdic\cp1146.py -> build\lib\ebcdic
  copying ebcdic\cp1147.py -> build\lib\ebcdic
  copying ebcdic\cp1148.py -> build\lib\ebcdic
  copying ebcdic\cp1148ms.py -> build\lib\ebcdic
  copying ebcdic\cp1149.py -> build\lib\ebcdic
  copying ebcdic\cp273.py -> build\lib\ebcdic
  copying ebcdic\cp277.py -> build\lib\ebcdic
  copying ebcdic\cp278.py -> build\lib\ebcdic
  copying ebcdic\cp280.py -> build\lib\ebcdic
  copying ebcdic\cp284.py -> build\lib\ebcdic
  copying ebcdic\cp285.py -> build\lib\ebcdic
  copying ebcdic\cp290.py -> build\lib\ebcdic
  copying ebcdic\cp297.py -> build\lib\ebcdic
  copying ebcdic\cp420.py -> build\lib\ebcdic
  copying ebcdic\cp424.py -> build\lib\ebcdic
  copying ebcdic\cp500.py -> build\lib\ebcdic
  copying ebcdic\cp500ms.py -> build\lib\ebcdic
  copying ebcdic\cp833.py -> build\lib\ebcdic
  copying ebcdic\cp838.py -> build\lib\ebcdic
  copying ebcdic\cp870.py -> build\lib\ebcdic
  copying ebcdic\cp871.py -> build\lib\ebcdic
  copying ebcdic\cp875.py -> build\lib\ebcdic
  copying ebcdic\__init__.py -> build\lib\ebcdic
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\ebcdic
  copying build\lib\ebcdic\cp037.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1025.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1047.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1097.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1112.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1122.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1123.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1140.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1141.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1142.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1143.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1144.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1145.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1146.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1147.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1148.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1148ms.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp1149.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp273.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp277.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp278.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp280.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp284.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp285.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp290.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp297.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp420.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp424.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp500.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp500ms.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp833.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp838.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp870.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp871.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\cp875.py -> build\bdist.win-amd64\wheel\.\ebcdic
  copying build\lib\ebcdic\__init__.py -> build\bdist.win-amd64\wheel\.\ebcdic
  running install_egg_info
  running egg_info
  writing ebcdic.egg-info\PKG-INFO
  writing dependency_links to ebcdic.egg-info\dependency_links.txt
  writing top-level names to ebcdic.egg-info\top_level.txt
  reading manifest file 'ebcdic.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\username\AppData\Local\Temp\pip-install-f8enp8mw\ebcdic\setup.py", line 71, in <module>
      test_suite='ebcdic.test.test_ebcdic',
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Miniconda2\envs\test\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Miniconda2\envs\test\lib\site-packages\wheel\bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "C:\Miniconda2\envs\test\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\Miniconda2\envs\test\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "C:\Miniconda2\envs\test\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
      self.run_command('egg_info')
    File "C:\Miniconda2\envs\test\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
      self.find_sources()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
      mm.run()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
      self.add_defaults()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
      self.read_manifest()
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
      self.filelist.append(line)
    File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
      path = convert_path(item)
    File "C:\Miniconda2\envs\test\lib\distutils\util.py", line 110, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/Users/roskakori/workspace/CodecMapper/LICENSE.txt' cannot be absolute
  ----------------------------------------
  ERROR: Failed building wheel for ebcdic
  Running setup.py clean for ebcdic
Failed to build ebcdic
Installing collected packages: ebcdic
  Running setup.py install for ebcdic ... error
    ERROR: Complete output from command 'C:\Miniconda2\envs\test\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-f8enp8mw\\ebcdic\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-3xnygb6a\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\ebcdic
    copying ebcdic\cp037.py -> build\lib\ebcdic
    copying ebcdic\cp1025.py -> build\lib\ebcdic
    copying ebcdic\cp1047.py -> build\lib\ebcdic
    copying ebcdic\cp1097.py -> build\lib\ebcdic
    copying ebcdic\cp1112.py -> build\lib\ebcdic
    copying ebcdic\cp1122.py -> build\lib\ebcdic
    copying ebcdic\cp1123.py -> build\lib\ebcdic
    copying ebcdic\cp1140.py -> build\lib\ebcdic
    copying ebcdic\cp1141.py -> build\lib\ebcdic
    copying ebcdic\cp1142.py -> build\lib\ebcdic
    copying ebcdic\cp1143.py -> build\lib\ebcdic
    copying ebcdic\cp1144.py -> build\lib\ebcdic
    copying ebcdic\cp1145.py -> build\lib\ebcdic
    copying ebcdic\cp1146.py -> build\lib\ebcdic
    copying ebcdic\cp1147.py -> build\lib\ebcdic
    copying ebcdic\cp1148.py -> build\lib\ebcdic
    copying ebcdic\cp1148ms.py -> build\lib\ebcdic
    copying ebcdic\cp1149.py -> build\lib\ebcdic
    copying ebcdic\cp273.py -> build\lib\ebcdic
    copying ebcdic\cp277.py -> build\lib\ebcdic
    copying ebcdic\cp278.py -> build\lib\ebcdic
    copying ebcdic\cp280.py -> build\lib\ebcdic
    copying ebcdic\cp284.py -> build\lib\ebcdic
    copying ebcdic\cp285.py -> build\lib\ebcdic
    copying ebcdic\cp290.py -> build\lib\ebcdic
    copying ebcdic\cp297.py -> build\lib\ebcdic
    copying ebcdic\cp420.py -> build\lib\ebcdic
    copying ebcdic\cp424.py -> build\lib\ebcdic
    copying ebcdic\cp500.py -> build\lib\ebcdic
    copying ebcdic\cp500ms.py -> build\lib\ebcdic
    copying ebcdic\cp833.py -> build\lib\ebcdic
    copying ebcdic\cp838.py -> build\lib\ebcdic
    copying ebcdic\cp870.py -> build\lib\ebcdic
    copying ebcdic\cp871.py -> build\lib\ebcdic
    copying ebcdic\cp875.py -> build\lib\ebcdic
    copying ebcdic\__init__.py -> build\lib\ebcdic
    running install_lib
    copying build\lib\ebcdic\cp037.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1025.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1047.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1097.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1112.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1122.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1123.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1140.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1141.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1142.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1143.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1144.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1145.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1146.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1147.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1148.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1148ms.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp1149.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp273.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp277.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp278.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp280.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp284.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp285.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp290.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp297.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp420.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp424.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp500.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp500ms.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp833.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp838.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp870.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp871.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\cp875.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    copying build\lib\ebcdic\__init__.py -> C:\Miniconda2\envs\test\Lib\site-packages\ebcdic
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp037.py to cp037.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1025.py to cp1025.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1047.py to cp1047.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1097.py to cp1097.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1112.py to cp1112.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1122.py to cp1122.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1123.py to cp1123.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1140.py to cp1140.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1141.py to cp1141.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1142.py to cp1142.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1143.py to cp1143.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1144.py to cp1144.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1145.py to cp1145.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1146.py to cp1146.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1147.py to cp1147.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1148.py to cp1148.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1148ms.py to cp1148ms.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp1149.py to cp1149.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp273.py to cp273.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp277.py to cp277.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp278.py to cp278.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp280.py to cp280.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp284.py to cp284.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp285.py to cp285.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp290.py to cp290.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp297.py to cp297.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp420.py to cp420.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp424.py to cp424.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp500.py to cp500.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp500ms.py to cp500ms.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp833.py to cp833.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp838.py to cp838.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp870.py to cp870.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp871.py to cp871.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\cp875.py to cp875.cpython-37.pyc
    byte-compiling C:\Miniconda2\envs\test\Lib\site-packages\ebcdic\__init__.py to __init__.cpython-37.pyc
    running install_egg_info
    running egg_info
    writing ebcdic.egg-info\PKG-INFO
    writing dependency_links to ebcdic.egg-info\dependency_links.txt
    writing top-level names to ebcdic.egg-info\top_level.txt
    reading manifest file 'ebcdic.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-install-f8enp8mw\ebcdic\setup.py", line 71, in <module>
        test_suite='ebcdic.test.test_ebcdic',
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Miniconda2\envs\test\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Miniconda2\envs\test\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "C:\Miniconda2\envs\test\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "C:\Miniconda2\envs\test\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Miniconda2\envs\test\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
        self.read_manifest()
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "C:\Miniconda2\envs\test\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
        path = convert_path(item)
      File "C:\Miniconda2\envs\test\lib\distutils\util.py", line 110, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/Users/roskakori/workspace/CodecMapper/LICENSE.txt' cannot be absolute
    ----------------------------------------
ERROR: Command "'C:\Miniconda2\envs\test\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-f8enp8mw\\ebcdic\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-3xnygb6a\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-f8enp8mw\ebcdic\
```
</p>
</details>

**Comment by roskakori** [comment]
Oh boy. When you need 3 updates to include a LICENSE file... 😭

I can reproduce this with Windows 10 and Python 3.7.3 from Anaconda3 but I have no clue why Python wants to use an absolute path here. The LICENSE.txt is included using the metadata in setup.cfg, which does not have an absolute path. So probably somewhere along the line of the build setuptools creates an absolute path.

There's a [question on stackoverflow](https://stackoverflow.com/questions/42360126/error-while-trying-to-install-sklearn-from-pycharm-arrayobject-h-cannot-be-abs/46073883#46073883) with similar issues when installing numpy. The solution (modifying distutils for the build) is less than reassuring though.

I have to look into this further.

**Comment by roskakori** [comment]
Note to self: possibly moving the license from setup.cfg to setup.py using `data_files` might solve this. See <https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script>.

**Comment by roskakori** [comment]
Oh well. I just changed the LICENSE from meta data to a data file, tested it on Windows, tested it macOS, built the sdist on macOS, released it only to find out that it still fails with a ValueError 😭.

Apparently sdist only works either works on Windows or Unix/macOS but not both with the same archive. 😞

Time to switch to wheel then.

**Comment by roskakori** [comment]
After a lot of mud wrestling with Python's craptacular package management ecosystem, ebcdic-1.1.1 is released and should install both on Windows and Unix/macOS.
